### ISSUE TITLE
Shameless rip-off

### ISSUE THREAD

**Issue by Natureshadow** [nikitasnv/materialize-select2#2]
This repository, or the biggest part of it, appears to be a shameless rip-off of other people's code, with the copyright information removed. The original work, as far as I could trace it back, seems to be https://github.com/kevzlou7979/select2-materialize

Maybe @kevzlou7979 wants to check this and probably take according actions.

**Comment by nikitasnv** [comment]
Ok, i can't get it why you write it after 3 years of repository creation.  It's true, plugin uses that repo, added information in readme.

**Comment by Natureshadow** [comment]
>Ok, i can't get it why you write it after 3 years of repository creation. 

Because I don't walk around investigating random GitHub repositories :D.
